# Generated by Django 4.2.3 on 2023-07-07 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('train', '0002_alter_ticket_train'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tTicket', to='train.train'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
