# Generated by Django 4.2.3 on 2023-07-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='rooms',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
    ]
