# Generated by Django 4.2.3 on 2023-07-07 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_room_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelreservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='hotel.room'),
        ),
    ]
