# Generated by Django 4.2.3 on 2023-07-07 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_alter_hotelreservation_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelreservation',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel'),
        ),
    ]
