# Generated by Django 4.2.3 on 2023-07-08 21:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('departure', models.DateField()),
                ('arrival', models.DateField()),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999)])),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('plane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pTicket', to='plane.plane')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
